server:
  port: 8080
  servlet:
    context-path: /devops
spring:
  application:
    name: k8s-paas
logging:
  level:
    root: info
k8sconfig:
  url : https://192.168.92.3:6443
  # 使用tiller的token
  token : eyJhbGciOiJSUzI1NiIsImtpZCI6IkdwTE92NHh3ckw0cmN2WEZvcVpENlR5SzJBb2hrd0gyc2RDcVFiOEN1MEUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJ0aWxsZXItdG9rZW4taGpqZ3IiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidGlsbGVyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYjg5ZTgxNmYtMWJmZi00MmM2LWIyNjktMjQ2ZjdkMWM2MDdjIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOnRpbGxlciJ9.g9Tv4qlTJ_3pScK2OfZoRk-HlWoBL3X9SCE-VT3EElNRjbm51AQUrX8CaPNZuVTax6vWIuM0oYTxKO89A43d3ca0-aoxGVK3hjov-nTcXZLMdC9raQEMDhWX-ALDs0WRs7l86KKzMnL9v7mYHicG0OeWE79g8F0MM-E0YONunEsOzbyWFv24IU4-5UsmYEltmXiY562rUNEIhm3sWM-YiZc_lP0sBdjr7xlLvnkE7mztR-4f3HftsuIn4grkarDc1PS5h6C-u2vX4UJC27JnAyTT4lsluWzwjuqNf7qGKT1BsMYJbhQGNBp_LXwvsPhOrVkIceXLSWkPsw0gda7aXw